spring:
  datasource:
    url: jdbc:mysql://db:3306/notification_system_db
    username: docker
    password: docker1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:ddl.sql
      data-locations: classpath:dml.sql