services:
  app:
    container_name: app-1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notification_system_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker1234
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: notification_system_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker1234
      MYSQL_ROOT_PASSWORD: mysql1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--bind-address=0.0.0.0'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: