### 상품이 없는 경우에 대한 테스트
POST http://localhost:8080/products/999999/notifications/re-stock

> {%
    client.test("Response status should be 404", function () {
        client.assert(response.status === 404);
    });
%}